# Generated by Django 4.0.4 on 2022-05-12 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_band_year_formed'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='description',
            field=models.CharField(default='desc 1', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annonce',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annonce',
            name='typeA',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='annonce',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
