# Generated by Django 4.0.4 on 2022-05-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_annonce_description_annonce_sold_annonce_typea_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='typeA',
            field=models.CharField(choices=[('Records', 'Disques'), ('Clothing', 'Vetements'), ('Posters', 'Affiches'), ('Miscellaneous', 'Divers')], max_length=50),
        ),
    ]
