# Generated by Django 4.0.4 on 2022-05-14 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_annonce_typea'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.band'),
        ),
    ]
