# Generated by Django 4.0.4 on 2022-05-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_annonce_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='old',
            field=models.IntegerField(default=0),
        ),
    ]
