# Generated by Django 4.0.4 on 2022-05-14 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_annonce_old'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='old',
        ),
    ]
